# Generated by Django 4.2.3 on 2023-10-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_category_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='serialNumber',
        ),
        migrations.AddField(
            model_name='item',
            name='consumable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='serialNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
