# Generated by Django 4.2.3 on 2023-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_desc_item_serialnumber_item_consumable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
