# Generated by Django 4.2.3 on 2023-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_booking_enddate_booking_endtime_booking_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
