# Generated by Django 4.2.3 on 2023-10-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_booking_order_quantity_booking_bookingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='occupied',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='status',
            field=models.CharField(default='Available'),
        ),
    ]
