# Generated by Django 4.2.3 on 2023-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_serviceitem_occupied_serviceitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
    ]
