# Generated by Django 4.2.3 on 2023-10-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.serviceitem'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='desc',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='serialNumber',
            field=models.CharField(max_length=500, verbose_name='Serial Number'),
        ),
    ]
