# Generated by Django 4.2.3 on 2023-10-31 13:24

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_booking_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[dashboard.models.Item.exempt_zero]),
        ),
        migrations.AlterField(
            model_name='item',
            name='serialNumber',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
