# Generated by Django 4.2.3 on 2023-11-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='item_assign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.serviceitem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_assign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='item',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
