# Generated by Django 4.2.3 on 2023-11-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_booking_item_assign_booking_service_assign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_assign',
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
