# Generated by Django 4.2.3 on 2023-11-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_booking_service_assign_alter_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='item_assign',
        ),
        migrations.AlterField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.serviceitem'),
        ),
    ]
