# Generated by Django 4.2.3 on 2023-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_booking_startdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='startTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
