# Generated by Django 4.2.3 on 2023-11-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_booking_enddate_remove_booking_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consumable',
            field=models.BooleanField(default=False),
        ),
    ]
