# Generated by Django 4.2.3 on 2023-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_item_consumable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consumable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
