# Generated by Django 4.2.3 on 2023-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_item_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
    ]
