# Generated by Django 4.2.3 on 2023-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serialNumber',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Serial Number'),
        ),
    ]
