# Generated by Django 4.2.3 on 2023-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_item_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDateTime',
            field=models.DateTimeField(null=True, verbose_name='Ending Date and Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDateTime',
            field=models.DateTimeField(null=True, verbose_name='Starting Date and Time'),
        ),
    ]
